ShopManagement/Controllers/AreaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceManagement.DAL;
using ServiceManagement.Models;

namespace ServiceManagement.Controllers
{
    public class AreaController : Controller
    {
        private readonly ApplicationDbContext _context;

        public AreaController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return _context.Area != null ?
                        View(await _context.Area.ToListAsync()) :
                        Problem("Entity set 'ApplicationDbContext.Area'  is null.");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Area == null)
            {
                return NotFound();
            }

            var area = await _context.Area
                .FirstOrDefaultAsync(m => m.Id == id);
            if (area == null)
            {
                return NotFound();
            }

            return View(area);
        }

        public IActionResult Create()
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name")] Area area)
        {
            if (ModelState.IsValid)
            {
                _context.Add(area);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(area);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Area == null)
            {
                return NotFound();
            }

            var area = await _context.Area.FindAsync(id);
            if (area == null)
            {
                return NotFound();
            }
            return View(area);
        }

       
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name")] Area area)
        {
            if (id != area.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(area);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!AreaExists(area.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(area);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Area == null)
            {
                return NotFound();
            }

            var area = await _context.Area
                .FirstOrDefaultAsync(m => m.Id == id);
            if (area == null)
            {
                return NotFound();
            }

            return View(area);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Area == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Area'  is null.");
            }
            var area = await _context.Area.FindAsync(id);
            if (area != null)
            {
                _context.Area.Remove(area);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool AreaExists(int id)
        {
            return (_context.Area?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ShopManagement/Controllers/StatusController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ServiceManagement.DAL;
using ServiceManagement.Models;

namespace ServiceManagement.Controllers
{
    public class StatusController : Controller
    {
        private readonly ApplicationDbContext _context;

        public StatusController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
              return _context.Status != null ? 
                          View(await _context.Status.ToListAsync()) :
                          Problem("Entity set 'ApplicationDbContext.Status'  is null.");
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Status == null)
            {
                return NotFound();
            }

            var status = await _context.Status
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        public IActionResult Create()
        {
            return View();
        }

        
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,time")] Status status)
        {
            if (ModelState.IsValid)
            {
                _context.Add(status);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Status == null)
            {
                return NotFound();
            }

            var status = await _context.Status.FindAsync(id);
            if (status == null)
            {
                return NotFound();
            }
            return View(status);
        }

     
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,time")] Status status)
        {
            if (id != status.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(status);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StatusExists(status.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(status);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Status == null)
            {
                return NotFound();
            }

            var status = await _context.Status
                .FirstOrDefaultAsync(m => m.Id == id);
            if (status == null)
            {
                return NotFound();
            }

            return View(status);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Status == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Status'  is null.");
            }
            var status = await _context.Status.FindAsync(id);
            if (status != null)
            {
                _context.Status.Remove(status);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool StatusExists(int id)
        {
          return (_context.Status?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

ShopManagement/Controllers/UserController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.UI.V4.Pages.Account.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Identity.Client;
using ServiceManagement.Helpers;
using ServiceManagement.Models;
using ServiceManagement.Services;
using ServiceManagement.ViewModels;
using ShopManagement.Controllers;
using System.Data;
using System.Security.Claims;

namespace ServiceManagement.Controllers
{

    public class UserController : Controller
    {
        public const string SessionKeyUserId = "_UserId";
        public const string SessionKeyRole = "_Role";
        public const string SessionKeyArea = "_Area";

        private UserService _userService;
        private RoleService _roleService;
        private AreaService _areaService;
        private IEmailService _emailService;

        public UserController(UserService userService, RoleService roleService, AreaService areaService, IEmailService emailService)
        {
            _userService = userService;
            _roleService = roleService;
            _areaService = areaService;
            _emailService = emailService;
        }
        [Authorize]
        [HttpGet]
        public IActionResult Index()
        {
            var users = _userService.GetAll();
            var roles = _roleService.GetAll();
            var area = _areaService.GetAll();




            return View(users);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var roles = _roleService.GetAll().Select(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = r.Name
            }).ToList();
            ViewBag.Roles = roles;


            var areas = _areaService.GetAll().Select(a => new SelectListItem
            {
                Value = a.Id.ToString(),
                Text = a.Name

            }).ToList();

            ViewBag.Areas = areas;

            return View("Create");
        }

        [Authorize(Roles = "Admin")]
        [HttpPost]
        public IActionResult Create(User user)
        {
            string hashedPassword = PasswordHasher.HashPassword(user.Password);
            user.Password = hashedPassword;
            _userService.Add(user);
            ModelState.Clear();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Login()
        {
            return View("Login");
        }

        
        

        

        [HttpPost]
        public ActionResult Login(User usr)
        {

            var user = _userService.GetAll().FirstOrDefault(u => u.Login == usr.Login);
            var roles = _roleService.GetAll();
            var roleDictionary = roles.ToDictionary(role => role.Id.ToString(), role => role.Name);
            if (user == null)
            {
                return View("Login");
            }
            bool isPassValid = PasswordHasher.VerifyPassword(usr.Password, user.Password);

            if (isPassValid)
            {
                var time = DateTime.Now;
                _userService.Update(user);
                var roleName = roleDictionary.ContainsKey(user.RoleId.ToString()) ? roleDictionary[user.RoleId.ToString()] : "Unknown Role";
                HttpContext.Session.SetInt32(SessionKeyUserId, user.Id);
                HttpContext.Session.SetString(SessionKeyRole, roleName);

                var claims = new List<Claim>
                    {
                        new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()),
                        new Claim(ClaimTypes.Name, user.Login),
                        new Claim(ClaimTypes.Role, roleName),
                    };

                var claimsIdentity = new ClaimsIdentity(
                    claims, CookieAuthenticationDefaults.AuthenticationScheme);

                HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity));


                return RedirectToAction("Index","Home");

            }
            return View("Login");

        }
         [HttpGet]
          public IActionResult SendEmailPasswd()
          {


              return View("SendEmailPasswd");
          }

          [HttpPost]

          public IActionResult SendEmailPasswd(string Email, User user)
          {

              var address = Email;

              UserEmailOptions userEmailOptions = new UserEmailOptions
              {
                  ToEmails = new List<string> { address },
                  PlaceHolders = new List<KeyValuePair<string, string>>()
                  {
                       new KeyValuePair<string, string>("{{Message}}", "Zapomniałeś hasła?"),
                      new KeyValuePair<string, string>("{{Link}}", "https://localhost:44320/User/NewPasswd")

                  }
              };
            
               _emailService.SendForgetPasswordEmail(userEmailOptions);
              ModelState.Clear();
               return RedirectToAction("Login");
          }

        [HttpGet]
        public IActionResult ChangePassword()
        {

            return View();
        }
        [HttpPost]
        public IActionResult ChangePassword(ChangePassViewModel changePass)
        {
            if (ModelState.IsValid)
            {
                var user = _userService.GetById(
                       int.Parse(HttpContext.User.Claims.Where(u => u.Type.Contains("nameidentifier")).FirstOrDefault().Value));


               
                
                    if (changePass.NewPassword != changePass.ConfirmPassword)
                    {
                        ViewBag.Valid = "Hasła się różnią";
                        return View();
                    }

                    var hashedPass = PasswordHasher.HashPassword(changePass.NewPassword);
                    user.Password = hashedPass;
                    _userService.Update(user);
                
                return RedirectToAction("Index", "Home");
            }
            return View();
        }



        [HttpGet]
        public async Task<IActionResult> Logout()
        {

            await HttpContext.SignOutAsync();

            return RedirectToAction("Login");
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var user = _userService.GetById(id);
            if (user == null)
                return NotFound();
            var roles = _roleService.GetAll().Select(r => new SelectListItem
            {
                Value = r.Id.ToString(),
                Text = r.Name
            }).ToList();

            ViewBag.Roles = roles;
            var areas = _areaService.GetAll().Select(a => new SelectListItem
            {
                Value = a.Id.ToString(),
                Text = a.Name

            }).ToList();

            ViewBag.Areas = areas;

            var model = new User
            {
                Id = id,
                Name = user.Name,
                LastName = user.LastName,
                Email = user.Email,
                Login = user.Login,
                Number = user.Number,
                RoleId = user.RoleId,
                AreaId = user.AreaId,
            };
            return View(model);
        }

        [HttpPost]
        public IActionResult Edit(User usr)
        {

            var user = _userService.GetById(usr.Id);
            if (user == null)
                return NotFound();
            user.Name = usr.Name;
            user.LastName = usr.LastName;
            user.Email = usr.Email;
            user.Login = usr.Login;
            user.Number = usr.Number;
            user.RoleId = usr.RoleId;
            user.AreaId = usr.AreaId;

            _userService.Update(user);
            return RedirectToAction("Index");

        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            var roles = _roleService.GetAll();
            var areas = _areaService.GetAll();
            var user = _userService.GetById(id);
            if (user == null)
                return NotFound();


            return View(user);
        }

        [HttpDelete]
        public IActionResult Delete(int id)
        {
            var user = _userService.GetById(id);
            if (user == null)
                return NotFound();
            _userService.Delete(id);
            return RedirectToAction("Index");
        }


    }
}

ShopManagement/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ServiceManagement</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ServiceManagement.styles.css" asp-append-version="true" />
    

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3" style="color:#F3F3F3; box-shadow: 0px 5px 8px 0px rgba(0, 0, 0, 0.25);">
            <div class="container-fluid">
                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index" style="padding:0; margin-left:30px;margin-right:40px">
                    <img src="~/logo.png" alt="logo" height="50px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                @if(User.IsInRole("Serwisant"))
                {
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        
                    <div class="dropdown nav-item">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Strona główna
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Ogłoszenia</a>
                        </div>
                    </div>
                    <div class="dropdown nav-item">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           Zadania
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-area="" asp-controller="Zadanie" asp-action="Index">Aktualne zadania</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Zadanie" asp-action="FinishedTask">Ukończone zadania</a>
                        </div>

                    </div>
                    <div class="dropdown nav-item">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Czas pracy
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-area="" asp-controller="WorkTimes" asp-action="Index">Twój czas pracy</a>
                            <a class="dropdown-item" asp-area="" asp-controller="WorkTimes" asp-action="Create">Dodaj czas pracy</a>
                        </div>

                    </div>
                    <div class="dropdown nav-item">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                           Dokumenty
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-area="" asp-controller="Document" asp-action="Index">Dokumenty</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Document" asp-action="Upload">Dodaj dokument</a>
                        </div>

                    </div>
                    
                    </div>
                  
                       
                        
                       
                  

                }
                @if(User.IsInRole("Admin"))
                {
                   
                            <div class="dropdown nav-item">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Strona główna
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Ogłoszenia</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Create">Dodaj ogłoszenie</a>
                                </div>
                            </div>
                            <div class="dropdown nav-item">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Użytkownicy
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Index">Użytkownicy</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="User" asp-action="Create">Dodaj użytkownika</a>
                                </div>
                                </div>
                            <div class="dropdown nav-item">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Zadania
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-area="" asp-controller="Zadanie" asp-action="Index">Aktualne zadania</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Zadanie" asp-action="Create">Dodaj zadanie</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Zadanie" asp-action="FinishedTask">Zakończone zadania</a>
                                </div>

                            </div>
                            <div class="dropdown nav-item">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Czas pracy
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-area="" asp-controller="WorkTimes" asp-action="Index">Czas pracy serwisantów</a>
                                </div>

                            </div>
                            <div class="dropdown nav-item">
                                <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Dokumenty
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a class="dropdown-item" asp-area="" asp-controller="Document" asp-action="Index">Dokumenty</a>
                                    <a class="dropdown-item" asp-area="" asp-controller="Document" asp-action="Upload">Dodaj dokument</a>
                                </div>

                            </div>
                    <div class="dropdown nav-item">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Rejony
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-area="" asp-controller="Area" asp-action="Index">Rejony</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Area" asp-action="Create">Dodaj rejon</a>
                        </div>

                    </div>
                    <div class="dropdown nav-item">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Priorytety
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-area="" asp-controller="Status" asp-action="Index">Priorytety zadań</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Status" asp-action="Create">Dodaj priorytet</a>
                        </div>

                    </div>
                           
                        
                }



                @if (User.IsInRole("Kierownik"))
                {

                    <div class="dropdown nav-item">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Strona główna
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Index">Ogłoszenia</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Home" asp-action="Create">Dodaj ogłoszenie</a>
                        </div>
                    </div>
                   
                    <div class="dropdown nav-item">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Zadania
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-area="" asp-controller="Zadanie" asp-action="Index">Aktualne zadania</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Zadanie" asp-action="Create">Dodaj zadanie</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Zadanie" asp-action="FinishedTask">Zakończone zadania</a>
                        </div>

                    </div>
                    <div class="dropdown nav-item">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Czas pracy
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-area="" asp-controller="WorkTimes" asp-action="Index">Czas pracy serwisantów</a>
                        </div>

                    </div>
                    <div class="dropdown nav-item">
                        <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dokumenty
                        </button>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                            <a class="dropdown-item" asp-area="" asp-controller="Document" asp-action="Index">Dokumenty</a>
                            <a class="dropdown-item" asp-area="" asp-controller="Document" asp-action="Upload">Dodaj dokument</a>
                        </div>

                    </div>
                    


                }
                <a class="btn" asp-controller="User" asp-action="Logout" id="dropItem" style="margin-right:40px"> Wyloguj się</a>

            </div>
        </nav>
        
    </header>
    <div class="container-fluid">
        <main role="main" >
            @RenderBody()
        </main>
    </div>


    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>